### ISSUE TITLE
add demo for tracking and auto-save-refresh

### ISSUE THREAD

**Issue by Remi-C** [Remi-C/interactive_map_tracking#10]
todo :
- propose out of the box demo for both, to help people wisualize and try it
- create a wiki page per demi, with screenshots

**Comment by Remi-C** [comment]
@yoyonel :  I already wrote the SQL scripts and produced test .shp file for tracking. I will upload it when I have correct access to internet

**Comment by yoyonel** [comment]
@Remi-C : Oki cool, good idea to have a demo out-of-the-box (install and configure SQL server it's not a easy task).

**Comment by Remi-C** [comment]
@yoyonel : 
- tracking : 
  - out of the box with shapefile(anybody)
  - script to create a postgis layer for multi-user tracking 
    (people interested in this should be serious enough to have a postgis)
  - auto save
  - script to create a postgis layer with trigger that demonstrate the interest of autosave
    (only intersting for PostGIS users, so they have a working postGIS! )

**Comment by Remi-C** [comment]
Closed, demo file are uploaded, plus demo page on wiki, plus screen
