### ISSUE TITLE
Add sponsor name & logo on website 

### ISSUE THREAD

**Issue by Remi-C** [Remi-C/interactive_map_tracking#18]
Add both sponsor (Terramobilita and ?)
@yoyonel : I don't know the name of the other one

**Comment by yoyonel** [comment]
ANR Project : TrafiPollu
http://www.agence-nationale-recherche.fr/projet-anr/?tx_lwmsuivibilan_pi2[CODE]=ANR-12-VBDU-0002
https://sites.google.com/site/trafipollu/

**Comment by Remi-C** [comment]
Here it is from Bahman
`This work was partly supported by Agence Nationale de la Recherche Grant ANR-12-VBDU-0002-09 (TrafiPollu project).`

**Comment by yoyonel** [comment]
Added in about page

**Comment by Remi-C** [comment]
This work was partly supported by Agence Nationale de 
la Recherche Grant ANR-12-VBDU-0002-09 (TrafiPollu project), and  by Thales Training & Simulation SAS  within FUI project TerraMobilita

**Comment by Remi-C** [comment]
This work was partly supported by Agence Nationale de 
la Recherche Grant ANR-12-VBDU-0002-09 (TrafiPollu project), and  by Thales Training & Simulation SAS  within FUI project TerraMobilita. The result of this works is under the co-property of IGN and Thales Training & Simulation SAS
