### ISSUE TITLE
Change plugin GUI

### ISSUE THREAD

**Issue by Remi-C** [Remi-C/interactive_map_tracking#19]
Small cosmetic changes : 
- v2 by default activated, change name for "Asynchronous tracking commit (smoooth)"
- Add 2 tabs : 
  - Tab "About", with correct credit
  - Tab "User Doc", displaying basic html with images (simplified "User Guide" of our wiki)

Work dispatchment : 
- @yoyonel GUI change in code
- @yoyonel Check that is it is possible to display simple html in the User doc
  then
- @Remi-C write simplified UserGuide in html, with images

**Comment by Remi-C** [comment]
according to @yoyonel  : 
added a mecanism to see github website from within plugin tab if connection works.
Else, loading a local page.
In both case, the page is resetted upon change of tab in GUI.

**Comment by Remi-C** [comment]
@yoyonel it should be okay now.
Both page are slim, so it should display nicely in "medium sized" tab

**Comment by yoyonel** [comment]
It's more complicated that i was thinking ... (many exceptions, special cases, strange behaviours :-/)
We need to track with signals the status of internet connection.
Qt have signals for the WebView widget. 
I've tracked the signal indicate that page is finished to load. 
This signal give the result of the loading (true = successful load, false = problem).
For online or offline version, it's the same mechanism.
With a simple state machine, we can track and decide in wich state we are (initialisation, online or offline mode).
One goal was to adapt the size of our plugin depend of the HTML content. 
For this i add a saving size tabs (for each tabs) and restoration when the user change the tab (we redefine a Qt event for this, attached to QDialog ResizeEvent)

Right now, it's not 100% operational, but it's a good beginning for this feature/enhancement (close to 90%)

**Comment by Remi-C** [comment]
@yoyonel  damn, this feature is missing :+1: 
"v2 by default activated, change name for "Asynchronous tracking commit (smoooth)""
Can't push to qgis like this

**Comment by Remi-C** [comment]
After some testing, as a user, I'm amazed by the level of quality of this 2 new tabs (User Doc , About).
It is easy to use, graphicaly nice and efficient, and user have access to all our doc.

@yoyonel : Just amazing.
Big Up!

**Comment by yoyonel** [comment]
@Remi-C : Thx man ! Keep in Progress ^^

**Comment by Remi-C** [comment]
@yoyonel Damn the V2 is still not used by default

**Comment by Remi-C** [comment]
@yoyonel from what I understood of code I have to change the .ui to change default state

**Comment by Remi-C** [comment]
@yoyonel 
The issue I'm talking about is non activated V2 y default.
Ok, I think I fixed it, but there is a major issue in design of QSettings usage.
All parameters of QSettings are not initilaized at the same time.
Morevover, this is a major design  mistake : why create local instance variable to store parameters, instead of creating get and set function. Local instance parameter are not thread safe, and the syncro between local parameter (in qsettings) and actual parameter (in qt gui object) is messy.

You'll have to check that.
