### ISSUE TITLE
Add a grouping mechanism for efficient tracking

### ISSUE THREAD

**Issue by Remi-C** [Remi-C/interactive_map_tracking#2]
Hey,
this is the thread dedicated to dev of a new mechanism to group saving of camera position.

**Comment by Remi-C** [comment]
from YoYo :

Le plug commence a se rapprocher du titre du projet du plug
C'est plus orienté vers l'interactif en terme de temps de réaction et d'impact sur le GUI de QGIS
La strat là mise en place (mais réglable) consiste:
- à désactiver la création de géométrie et commit sur la base tant qu'il y a un mouvement sur la map.
  Le mouvement décrit (selon moi) un mode de navigation, comme pour rechercher sa zone de travail
- Dès qu'il y a un "arrêt" de navigation ça lance un timer (sur un seuil) pour construire la géométrie
- Dès que la géométrie est construite/présente dans un layer on lance un timer pour le commit  (un seuil cette étape)

Le truc sympa,
c'est que tout est gardé en mémoire en attendant d'avoir "du temps pour consommer les requêtes".

Les avantages :
- ça n'impact pas la navigation, zoom dezoom, chercher une zone, etc ...
- les coûts de :
  - constructions
  - send to layer
  - send to DB/Disk
    sont ... étalés sur le temps (reglable)

Drawbacks:
- Ce n'est pas du temps réel pour visualiser les extents (tracking position) sur la map

Le drawback est a prendre avec des pincettes,
car ça reste réglable et ça dépend de ce qu'on souhaite comme comportement

**Comment by yoyonel** [comment]
Done in V2.00, soon released ^^
