### ISSUE TITLE
Avoid saving a track (TrackingPosition) when we modify a layer (AutoSaveRefresh)

### ISSUE THREAD

**Issue by yoyonel** [Remi-C/interactive_map_tracking#25]
The problem comes from our current approach to refresh the map (epsilon zoom on MapCanvas) that provoke a canvaxextentChanged and launch the tracking. 
To avoid this, i add a filter on the actual extent (to save) and the last committed. 
If layers are different (with a proper epsilon value), we continue the tracking process else we cancel the tracking.

**Comment by Remi-C** [comment]
@yoyonel DO you mean that every time we edit a feature in a layer, it adds a camera_position to the tracking layer?
