### ISSUE TITLE
Edit dev doc to a minimal level

### ISSUE THREAD

**Issue by Remi-C** [Remi-C/interactive_map_tracking#3]
The dev doc should be at a minimum level before releasing to first version milestone@"Release 1.0"
This include
- a little bit of high level dev doc (principle of each feature implementation, pointer to most important functions)
- a little bit of issue specific doc, that is explain what was tried but unsuccessful.

**Comment by Remi-C** [comment]
Here is the list of pre-filled doc
- https://github.com/Remi-C/interactive_map_tracking/wiki/%5Bdev%5D-RoadMap  
  Simply details the step (about 4-5) for grouping of camera tracking event
- https://github.com/Remi-C/interactive_map_tracking/wiki/%5Bdev%5D-Detailled-doc  
  I already detailed as far as I knew the plugin mechanism. 
  - It need to be completed with some real function name (2-3, only most important), and real event name (same, only most important)
  - The saving behaviour is not complete (I don't know more)

When citing actual function name, you can use the ` sign before and after, it will create an inline code `like this`
You can also add 4 spaces to create a code block if you want to cite several line  

```
this is a code block
Yeah
my function blabla
```

**Comment by Remi-C** [comment]
@yoyonel : this need to be done to close the milestone !

**Comment by Remi-C** [comment]
@yoyonel you can use the command 
`[[/images/plugin/dev_plugin_principle_schema.png]]`
to include the image in the wiki.
In the site, you have to use (without extra space)
  `![](/Remi-C/interactive_map_tracking.wiki//images/plugin/dev_plugin_principle_schema.png)`

**Comment by yoyonel** [comment]
Update and add documentations for dev sides of our project.
Add events/signals with (briefs) descriptions and urls/link to them (in QGIS API documentation, can be useful for futur dev/contributors)

**Comment by Remi-C** [comment]
adding the schema to wiki/dev main page
