### ISSUE TITLE
crash qgis when trying ot delete the tracking layer

### ISSUE THREAD

**Issue by Remi-C** [Remi-C/interactive_map_tracking#34]
To reproduce : use a shapefile for tracking, track some
then try to remove tracking layer from qgis (Ctrl D)
It crashes QGIS

**Comment by yoyonel** [comment]
Oki i think i see the problem (come from our asynch approach). Can be solved easily ^^

**Comment by yoyonel** [comment]
I remove "Can be solved easily", i was too confident lol

**Comment by Remi-C** [comment]
Good,
As "agile" suggest,
don't hesitate to create new tickets for sub-goal
if one ticket is too big
Rémi

2015-03-18 11:52 GMT+01:00 yoyonel notifications@github.com:

**Comment by yoyonel** [comment]
@Remi-C : Need to be tested before merging with master branch.

**Comment by Remi-C** [comment]
@yoyonel : still the same bug ..
Courage !

**Comment by Remi-C** [comment]
Corrected by last commit

**Comment by yoyonel** [comment]
Youhouououououuu ^^
