### ISSUE TITLE
tracking : time is not precise enough (up to second, not millisecond)

### ISSUE THREAD

**Issue by Remi-C** [Remi-C/interactive_map_tracking#4]
The time written in database is not precise enough.
Its precision is second, it should be milliseconds.

Having second is dangerous because many w_time are identical.
@yoyonel can you look into it to check weither it can be done before milestone Release?

**Comment by yoyonel** [comment]
Done

**Comment by Remi-C** [comment]
Nice !
Notice that we can still comment, even when the issue is closed.
tested on win7, it works! 
Data base fine with this new format
