### ISSUE TITLE
plugin does'nt install well from qgis depot

### ISSUE THREAD

**Issue by Remi-C** [Remi-C/interactive_map_tracking#48]
@yoyonel :  the plugin has been reported to not install well from QGIS plugin repository, 
with plug version 2.8.

**Comment by glw** [comment]
OS: Windows 7
Version: QGIS 2.12.1

install issues:
- From plugin repository:
  1A. With proxy settings off , will not install. No crash.
  1B. With proxy setting on, specifying "Default". Plugin installs but with critical error. QGIS crashes.     QGIS will not restart from this point.

From this point I think I will uninstall. And start fresh and try QGIS 2.8 for this plugin.  
It looks promising though and I look forward to using it.

**Comment by Remi-C** [comment]
Hey @glw,
the issue seemed to be related to the plugin folder name.
We changed it and re uploaded the pluggin.
Now it install fine on 2.12 on my computer.
DO you still have issues?
Cheers
