### ISSUE TITLE
Popup size wrong on GNOME3

### ISSUE THREAD

**Issue by pcav** [Remi-C/interactive_map_tracking#6]
And not resizable. See attached pics. Font size in the second image too small.
![inter2](https://cloud.githubusercontent.com/assets/691842/6344526/1430f592-bbfa-11e4-83a9-76b21b68bea8.png)
![inter1](https://cloud.githubusercontent.com/assets/691842/6344527/14326ddc-bbfa-11e4-9091-9e07d0de4d37.png)

**Comment by Remi-C** [comment]
Thank you Paolo for reviewing our plug-in.
Our dev documentation is a work in progress (#3 )
https://github.com/Remi-C/interactive_map_tracking/wiki/%5Bdev%5D-Detailled-doc

I reproduced the bug.
Cheers

**Comment by Remi-C** [comment]
Thank you Paolo for reviewing our plug-in.
Our dev documentation is a work in progress (#3 )
https://github.com/Remi-C/interactive_map_tracking/wiki/%5Bdev%5D-Detailled-doc

I reproduced the bug.
Cheers

**Comment by Remi-C** [comment]
Thank you Paolo for reviewing our plug-in.
Our dev documentation is a work in progress ( #3 )
https://github.com/Remi-C/interactive_map_tracking/wiki/%5Bdev%5D-Detailled-doc

I reproduced the bug.
Cheers

**Comment by Remi-C** [comment]
Thank you @pcav for reviewing uour plugin, any comment is welcom.
We have a work in progress by @yoyonel for dev doc (#3)
https://github.com/Remi-C/interactive_map_tracking/wiki/%5Bdev%5D-Detailled-doc
Cheers,
Rémi-C

**Comment by pcav** [comment]
BTW: as you can see from the screenshot, the Close / OK buttons are missing in Gnome3. An issue common also to other plugins.

**Comment by Remi-C** [comment]
Do you know a good direction to look for a fix?
Is this specific to PyQT or QGIS?

**Comment by yoyonel** [comment]
I work under Mintx64/KDE Desktop and Windows 7 (x64). 
No issues on this OS/Windows Manager.
I will try to switch under Gnome3 soon. 
Thx for you comment @pcav ^^

**Comment by pcav** [comment]
Please have a look to OL3 plugin, which solved the issue recently. Even better, ask on the mailing list, so more peop0le will be aware of this.

**Comment by Remi-C** [comment]
Thanks @pcav ,
@yoyonel , OL3 is the plugin Open Layer 3 that is [here](https://plugins.qgis.org/plugins/openlayers_plugin/), I let you start the thread ?

**Comment by Remi-C** [comment]
Thanks @pcav ,
@yoyonel , OL3 is the plugin Open Layer 3 that is [here](https://plugins.qgis.org/plugins/ol3/), I let you start the thread ?

**Comment by yoyonel** [comment]
@Remi-C , I don't see anything about our problem in issues tracking : https://github.com/volaya/qgis-ol3/issues

**Comment by Remi-C** [comment]
I guess we have to look to UI files to find what is different from ours.
Maybe they don't use the same QT classes as us : 
- [UI](https://github.com/volaya/qgis-ol3/blob/994dfb65d464fc4e3143bcfa4133cb45438e7398/ui_maindialog.ui)
- [UI_py](https://github.com/volaya/qgis-ol3/blob/9b5dd87b8fabeae70b2e450a73e10a67ec58c457/ui_maindialog.py)

**Comment by pcav** [comment]
It's a recent change in the code, not a ticket. Sorry I have no time to check now.

**Comment by yoyonel** [comment]
Tested on :
$ gnome-session --version
gnome-session 3.9.90
Seems to work properly now.

**Comment by Remi-C** [comment]
@pcav : the problem seems to be fixed.
The solution seems to be to not set size :

```
# dont set size like this --> self.dlg.setFixedSize(self.dlg.size())
```

To use a layout 
    <layout class="QGridLayout" name="gridLayout">

Then allow resizing

```
<layout class="QFormLayout" name="formLayout_6">
<property name="fieldGrowthPolicy">
 <enum>QFormLayout::AllNonFixedFieldsGrow</enum>
</property>
```

**Comment by yoyonel** [comment]
Yep, but it's not just this line to fix the problem.
I rearranged layouts for each tab in our plugin windows.
Add forms layout and spacersto get a good behaviour when resized
