### ISSUE TITLE
tracking : Error when srs=4326 and threshold is low

### ISSUE THREAD

**Issue by Remi-C** [Remi-C/interactive_map_tracking#7]
To reproduce : 
create  a shapefile of type polygon with user_id::text and w_time::text
Set the shapefile srs to 4326 (WGS84).
WGS84 unit is not meter but degree.

Setting the threshold to 1 or 0.1 or 0,1 slow down conserably the plugin,
finally freezing qgis with one CPU fully occuped.

**Comment by Remi-C** [comment]
Precision :
to reproduce ++ :
- set threshold to 1, zoom/dezoom until something is tracked.
- Zoom
- Change threshold to 0.1
- zoom dezoom.
- Go to a zoom level of type N:1
- set threshold to 1

-> Infinite loop

**Comment by Remi-C** [comment]
@yoyonel :  can you assign yourself plz, I can't do it

**Comment by yoyonel** [comment]
I think it's a temporary bugs (according with our current technology for saving/tracking the position).
With the next realease (enqueue task & distributed costs), i'm pretty sure that the bug will vanish ^^

@Remi-C : can i close this one too ?

**Comment by Remi-C** [comment]
closed because not rlevant anmore
