### ISSUE TITLE
tracking : error when switching srs while tracking on shapefile

### ISSUE THREAD

**Issue by Remi-C** [Remi-C/interactive_map_tracking#8]
To reproduce : 
- create a tracking shapefile in WGS84 (4326)
- track some geometry
- set threshold to 1 
- track more
- change shapefile SRS to IGNF:LAMB93
- track
  --> produce the error message

error is :
``Traceback (most recent call last):
  File " \interactive_map_tracking\interactive_map_tracking.py", line 505, in canvasExtentsChangedAndRenderComplete
    self.update_track_position()
  File " \interactive_map_tracking\interactive_map_tracking.py", line 752, in update_track_position
    list_points = [xform.transform(point) for point in list_points_from_mapcanvas]
QgsCsException: Poursuivre la transformation de
(-24479.530208, 57767.106935)
PROJ.4: +proj=longlat +datum=WGS84 +no_defs +to +proj=lcc +nadgrids=@null +a=6378137.0000 +rf=298.2572221010000 +lat_0=46.500000000 +lon_0=3.000000000 +lat_1=44.000000000 +lat_2=49.000000000 +x_0=700000.000 +y_0=6600000.000 +units=m +no_defs
Erreur: latitude or longitude exceeded limits`

**Comment by Remi-C** [comment]
assign @yoyonel

**Comment by Remi-C** [comment]
Bonus : 
when canceling error, zooming to track result in infinite loop

**Comment by yoyonel** [comment]
Oki i see the problem.
Right now we don't follow the SRS switch on layer (tracking layer).
We need to intercepted the signal from QGIS Gui. Not difficult.

**Comment by Remi-C** [comment]
@yoyonel : 
please don't, better to change the way the threshold is defined so it is independant of srs
 (see #9)

**Comment by yoyonel** [comment]
Anyway i will add a catch exception on this transformation

**Comment by Remi-C** [comment]
Good idea
